import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // One sidebar per top-level section, scoped to its own folder, so the
  // left panel only shows the section currently being browsed.
  internalOperationsSidebar: [
    {type: 'autogenerated', dirName: '01-internal-operations'},
  ],
  studyMaterialsSidebar: [
    {type: 'autogenerated', dirName: '02-study-materials'},
  ],
  clientsSidebar: [{type: 'autogenerated', dirName: '03-clients'}],
};

export default sidebars;
